spring:
  profiles:
    include: token
  data:
    mongodb:
      host: localhost
      port: 27017
      username: crawler
      password: crawler123
      database: crawlerdb
      auto-index-creation: true

crawler:
  cron:
    trigger: "0 0/10 * * * ?"